/* -LICENSE-START-
** Copyright (c) 2018 Blackmagic Design
**
** Permission is hereby granted, free of charge, to any person or organization
** obtaining a copy of the software and accompanying documentation covered by
** this license (the "Software") to use, reproduce, display, distribute,
** execute, and transmit the Software, and to prepare derivative works of the
** Software, and to permit third-parties to whom the Software is furnished to
** do so, all subject to the following:
** 
** The copyright notices in the Software and this entire statement, including
** the above license grant, this restriction and the following disclaimer,
** must be included in all copies of the Software, in whole or in part, and
** all derivative works of the Software, unless such copies or derivative
** works are solely in the form of machine-executable object code generated by
** a source language processor.
** 
** THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
** IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
** FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
** SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
** FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
** ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
** DEALINGS IN THE SOFTWARE.
** -LICENSE-END-
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

using BMDSwitcherAPI;

namespace SimpleSwitcherExampleCSharp
{
	class Program
	{
		static long GetInputId(IBMDSwitcherInput input)
		{
			long id;
			input.GetInputId(out id);
			return id;
		}
        static string GetLongName(IBMDSwitcherInput input)
        {
            string name;
            input.GetLongName(out name);
            return name;
        }

        static _BMDSwitcherPortType GetPortType(IBMDSwitcherInput input)
        {
            _BMDSwitcherPortType type;
            input.GetPortType(out type);
            return type;
        }
        static int Main(string[] args)
        {
            if (args.Length < 1)
            {
                Console.Error.WriteLine("使い方: SimpleSwitcherExampleCSharp.exe <入力ID> [wipe|mix] [IPアドレス]");
                Console.Error.WriteLine("例1: SimpleSwitcherExampleCSharp.exe 2");
                Console.Error.WriteLine("例2: SimpleSwitcherExampleCSharp.exe 2 mix");
                Console.Error.WriteLine("例3: SimpleSwitcherExampleCSharp.exe 2 wipe 192.168.10.240");
                return 1;
            }

            long targetId;
            if (!long.TryParse(args[0], out targetId))
            {
                Console.Error.WriteLine($"エラー: 入力ID '{args[0]}' は数値ではありません。");
                return 1;
            }

            string transitionName = (args.Length >= 2) ? args[1].ToLowerInvariant() : "wipe";
            string switcherIp = (args.Length >= 3) ? args[2] : "";

            bool useWipe;
            if (transitionName == "wipe")
            {
                useWipe = true;
            }
            else if (transitionName == "mix")
            {
                useWipe = false;
            }
            else
            {
                Console.Error.WriteLine($"エラー: トランジション種別 '{transitionName}' は無効です。wipe または mix を指定してください。");
                return 1;
            }

            try
            {
                IBMDSwitcherDiscovery discovery = new CBMDSwitcherDiscovery();

                IBMDSwitcher switcher;
                _BMDSwitcherConnectToFailure failureReason;
                discovery.ConnectTo(switcherIp, out switcher, out failureReason);

                if (switcher == null)
                {
                    Console.Error.WriteLine($"ATEMへの接続に失敗しました。IP='{switcherIp}' Reason={failureReason}");
                    return 1;
                }

                Console.WriteLine(string.IsNullOrEmpty(switcherIp)
                    ? "Connected to switcher (USB/auto)"
                    : $"Connected to switcher ({switcherIp})");

                var atem = new AtemSwitcher(switcher);

                IBMDSwitcherMixEffectBlock me0 = atem.MixEffectBlocks.First();
                IBMDSwitcherTransitionParameters me0TransitionParams = me0 as IBMDSwitcherTransitionParameters;
                IBMDSwitcherTransitionWipeParameters me0WipeTransitionParams = me0 as IBMDSwitcherTransitionWipeParameters;
                IBMDSwitcherTransitionMixParameters me0MixTransitionParams = me0 as IBMDSwitcherTransitionMixParameters;

                long programId;
                long previewId;
                int inTransition;

                me0.GetProgramInput(out programId);
                me0.GetPreviewInput(out previewId);
                me0.GetInTransition(out inTransition);

                var externalInputs = atem.SwitcherInputs
                    .Where(i => {
                        _BMDSwitcherPortType type;
                        i.GetPortType(out type);
                        return type == _BMDSwitcherPortType.bmdSwitcherPortTypeExternal;
                    })
                    .ToList();

                IBMDSwitcherInput targetInput = externalInputs
                    .FirstOrDefault(i => GetInputId(i) == targetId);

                if (targetInput == null)
                {
                    Console.Error.WriteLine($"エラー: 入力ID {targetId} は見つかりませんでした。");
                    return 1;
                }

                if (programId == targetId)
                {
                    Console.WriteLine("指定した入力はすでに Program 側です。切り替え不要です。");
                    return 0;
                }

                Console.WriteLine($"Current Program ID : {programId}");
                Console.WriteLine($"Current Preview ID : {previewId}");
                Console.WriteLine($"Target Preview ID  : {targetId}");
                Console.WriteLine($"Target Input Name  : {GetLongName(targetInput)}");

                Console.WriteLine("Setting preview input");
                me0.SetPreviewInput(targetId);

                //System.Threading.Thread.Sleep(1000);
                Console.WriteLine("Setting next transition selection");
                me0TransitionParams.SetNextTransitionSelection(
                    _BMDSwitcherTransitionSelection.bmdSwitcherTransitionSelectionBackground);

                Console.WriteLine("Setting next transition style");
                if (useWipe)
                {
                    me0TransitionParams.SetNextTransitionStyle(
                        _BMDSwitcherTransitionStyle.bmdSwitcherTransitionStyleWipe);

                    me0WipeTransitionParams.SetPattern(
                        _BMDSwitcherPatternStyle.bmdSwitcherPatternStyleRectangleIris);
                    me0WipeTransitionParams.SetRate(60);
                }
                else
                {
                    me0TransitionParams.SetNextTransitionStyle(
                        _BMDSwitcherTransitionStyle.bmdSwitcherTransitionStyleMix);

                    // Mix の rate も設定しておく
                    me0MixTransitionParams.SetRate(30);
                }


                Console.WriteLine("Performing auto transition");
                me0.PerformAutoTransition();

                // 少し待って反映を待つ
                for (int i = 0; i < 100; i++)
                {
                    int currentInTransition;
                    me0.GetInTransition(out currentInTransition);

                    if (currentInTransition != 0)
                        break;

                    System.Threading.Thread.Sleep(20);
                }

                // トランジション終了待ち
                for (int i = 0; i < 300; i++)
                {
                    int currentInTransition;
                    me0.GetInTransition(out currentInTransition);

                    if (currentInTransition == 0)
                        break;

                    System.Threading.Thread.Sleep(20);
                }

                // 最終状態を確認
                long newProgramId;
                long newPreviewId;
                me0.GetProgramInput(out newProgramId);
                me0.GetPreviewInput(out newPreviewId);

                Console.WriteLine($"New Program ID     : {newProgramId}");
                Console.WriteLine($"New Preview ID     : {newPreviewId}");

                Console.WriteLine("Switch completed.");
                return 0;

            }
            catch (Exception ex)
            {
                Console.Error.WriteLine("エラー: " + ex.Message);
                return 1;
            }
        }

    }

	internal class AtemSwitcher
	{
		private IBMDSwitcher switcher;

		public AtemSwitcher(IBMDSwitcher switcher)
		{
			this.switcher = switcher;
		}

		public IEnumerable<IBMDSwitcherMixEffectBlock> MixEffectBlocks
		{
			get
			{
				// Create a mix effect block iterator
				IntPtr meIteratorPtr;
				switcher.CreateIterator(typeof(IBMDSwitcherMixEffectBlockIterator).GUID, out meIteratorPtr);
				IBMDSwitcherMixEffectBlockIterator meIterator = Marshal.GetObjectForIUnknown(meIteratorPtr) as IBMDSwitcherMixEffectBlockIterator;
				if (meIterator == null)
					yield break;

				// Iterate through all mix effect blocks
				while (true)
				{
					IBMDSwitcherMixEffectBlock me;
					meIterator.Next(out me);

					if (me != null)
						yield return me;
					else
						yield break;
				}
			}
		}

		public IEnumerable<IBMDSwitcherInput> SwitcherInputs
		{
			get
			{
				// Create an input iterator
				IntPtr inputIteratorPtr;
				switcher.CreateIterator(typeof(IBMDSwitcherInputIterator).GUID, out inputIteratorPtr);
				IBMDSwitcherInputIterator inputIterator = Marshal.GetObjectForIUnknown(inputIteratorPtr) as IBMDSwitcherInputIterator;
				if (inputIterator == null)
					yield break;

				// Scan through all inputs
				while (true)
				{
					IBMDSwitcherInput input;
					inputIterator.Next(out input);

					if (input != null)
						yield return input;
					else
						yield break;
				}
			}
		}
	}
}
